services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: guilherme
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: e-commerce-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guilherme -d e-commerce-db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - e-commerce-network

volumes:
  postgres_data:
    driver: local

networks:
  e-commerce-network:
    driver: bridge
