services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_USERNAME=root
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_USERNAME=guilherme
      - MONGODB_PASSWORD=123456
      - MONGODB_DATABASE=e-commerce-db
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ADVERTISED_HOSTNAME=localhost
    volumes:
      - mongodb_data:/bitnami/mongodb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - e-commerce-network

volumes:
  mongodb_data:
    driver: local

networks:
  e-commerce-network:
    driver: bridge